# Generated by Django 5.0.5 on 2024-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_n_care', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
